
[W NNPACK.cpp:51] Could not initialize NNPACK! Reason: Unsupported hardware.
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lechapelier/Documents/StageM2/Internship-Ethical-MORL/moral_rl/moral/evaluate_ppo_and_discrim.py", line 198, in <module>
    rand_trajectories = pickle.load(open(rand_filename, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'generated_data/generators/Peschl/ppo_rand_v3_[0, 1, 0, 1].pt'
([0.8461538461538461, 9.153846153846153, 0.38461538461538464, -0.6923076923076923], [0.9483713850721501, 1.0986812966989, 0.7378202343558031, 0.8213137116947161])